name: CocoaPods

on:
  push:
    tags:
      - "*.*.*"

jobs:
  push:
    env:
      COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
    runs-on: macos-latest
    steps:
      - name: Check-out repo
        uses: actions/checkout@v4
      - name: Push to Cocoapods
        run: pod spec lint KinegramEmrtdConnector.podspec && pod trunk push KinegramEmrtdConnector.podspec
